#!/usr/bin/env python
###
# XEN CLEAN INSTALLER
# Main script
#
# written by Andrew Peace
# Copyright XenSource Inc. 2006

# user-interface stuff:
import tui
import generalui
import uicontroller

# backend
import backend

ui_package = tui

def main():
    ui_package.init_ui()

    results = { 'ui-package': ui_package }

    seq = [ ui_package.welcome_screen,
            generalui.disk_selection ]
    uicontroller.runUISequence(seq, results)

    backend.performStage1Install(results)

    #seq = [ ui_package.get_root_password,
    #        ui_package.determine_basic_network_config,
    #        ui_package.need_manual_hostname,
    #        ui_package.installation_complete ]
    seq = [ ui_package.installation_complete ]

    uicontroller.runUISequence(seq, results)
    
    ui_package.end_ui()


if __name__ == "__main__":
    main()
2
