#!/bin/bash
# Copyright (c) 2005-2006 XenSource, Inc. All use and distribution of this 
# copyrighted material is governed by and subject to terms and conditions 
# as licensed by XenSource, Inc. All other rights reserved.
# Xen, XenSource and XenEnterprise are either registered trademarks or 
# trademarks of XenSource Inc. in the United States and/or other countries.

###
# Attempt to find additional hardware using modules.pcimap

while read IGNORE ID IGNORE ; do
    VENDOR=`echo $ID | cut -b1-4`
    DEVICE=`echo $ID | cut -b5-8`
    DEVENTRY="0x0000${VENDOR} 0x0000${DEVICE}"

    cat /lib/modules/$(uname -r)/modules.pcimap | grep "$DEVENTRY" | cut -d ' ' -f 1
done < /proc/bus/pci/devices
