#!/bin/bash
###
# Attempt to find additional hardware using modules.pcimap

while read IGNORE ID IGNORE ; do
    VENDOR=`echo $ID | cut -b1-4`
    DEVICE=`echo $ID | cut -b5-8`
    DEVENTRY="0x0000${VENDOR} 0x0000${DEVICE}"

    cat /lib/modules/$(uname -r)/modules.pcimap | grep "$DEVENTRY" | cut -d ' ' -f 1
done < /proc/bus/pci/devices
