#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-2.0-only

import sys
import os
import os.path
import signal
import subprocess

# user interface:
import tui
import tui.init
import tui.progress

import hwsetup
import install
import netutil
from constants import MultipathConfig
import diskutil
import util
from xcp import logger

from version import *

def sig_term(x, y):
    logger.log("Killed by another instance, terminating")
    os.system('/usr/bin/clear')
    sys.exit(0)

def main(args):
    # log to tty3
    logger.openLog('/dev/tty3')
    logger.openLog('/tmp/install-log')

    tty = None
    signal.signal(signal.SIGTERM, sig_term)
    try:
        tty = os.path.basename(os.readlink('/proc/self/fd/0'))
        pidfile = open('/var/run/installer-%s.pid' % tty, 'w')
        print(os.getpid(), file=pidfile)
        pidfile.close()
    except:
        pass

    ui = tui
    interactive = True
    answer_device = 'all'
    answer_config = 'dhcp'
    init_network = False
    reboot = False
    answerfile_address = None
    answerfile_script = None
    mpath = MultipathConfig.IF_MULTIPLE
    netdev_map = []

    try:
        installer_version = subprocess.check_output(
            ['rpm', '-q', '--qf', '%{VERSION}-%{RELEASE}', 'host-installer'])
    except Exception:
        installer_version = 'unknown'

    logger.log("%s Setup - Version %s" % (PRODUCT_BRAND or PLATFORM_NAME, PRODUCT_VERSION_TEXT))
    logger.log("Installer Version %s" % (installer_version,))
    logger.log("Command line args: %s" % str(args))
    for (opt, val) in args.items():
        if opt == "--answerfile":
            answerfile_address = val
            interactive = False
            if not val.startswith('file://'):
                init_network = True
        elif opt == "--rt_answerfile":
            answerfile_address = val
            interactive = False
            if not val.startswith('file://'):
                init_network = True
            ui = None
            logger.openLog(sys.stdout)
        elif opt == "--answerfile_generator":
            answerfile_script = val
            interactive = False
            if not val.startswith('file://'):
                init_network = True
        elif opt in ['--answerfile_device', '--network_device']:
            answer_device = val.lower()
            init_network = True
        elif opt == '--network_config':
            answer_config = val.lower()
        elif opt == "--reboot":
            reboot = True
        elif opt == "--device_mapper_multipath":
            if val.lower() in [ "disabled", "false", "0", "no" ]:
                mpath = MultipathConfig.DISABLED
            elif val.lower() in [ "if-multiple" ]:
                mpath = MultipathConfig.IF_MULTIPLE
            elif val.lower() in [ "enabled", "true", "1", "yes", "force"]:
                mpath = MultipathConfig.ENABLED
        elif opt == "--map_netdev":
            netdev_map = val

    # start the user interface:
    if ui:
        # switch to ISO 8859-1 mode so line drawing characters work as expected on
        # vt100 terminals.
        print("\033%@")

        logger.log("Starting 'init' user interface on %s" % tty)
        ui.init_ui()

    # let the user choose what they would like to do:
    if interactive:
        # choose keymap
        kmap = ui.init.get_keymap()

        if tty:
            try:
                # terminate any additional instances of the installer
                for p in os.listdir('/var/run'):
                    if p != 'installer-%s.pid' % tty and p.startswith('installer-'):
                        f = open('/var/run/'+p)
                        pid = int(f.readline())
                        f.close()
                        logger.log("Killing installer with pid %d" % pid)
                        os.kill(pid, signal.SIGTERM)
            except:
                pass

        args['--keymap'] = kmap
        logger.log("Loading keymap %s" % kmap)
        util.runCmd2(["/bin/loadkeys", kmap])

    # Generate interface order rules, which will be saved later
    netutil.generate_interface_rules(netdev_map)

    # The management interface screen shows each NIC's link state.
    if ui:
        netutil.setAllLinksUp()

    # Interactive installs bring the hardware up later, after the driver
    # selection (see hwsetup).
    if not interactive:
        try:
            hwsetup.bring_up_hardware(ui, mpath,
                                      answer_device if init_network else None,
                                      answer_config)
        except Exception as e:
            logger.logException(e)
            if ui:
                ui.exn_error_dialog("install-log", False, interactive)
                return reboot
            raise

    logger.log("Starting installation/upgrade/restore")

    rc = install.go(ui, args, answerfile_address, answerfile_script)

    if ui:
        ui.end_ui()

    # Bring down multipath devices to ensure they're flushed
    if mpath != MultipathConfig.DISABLED:
        diskutil.mpath_disable()

    # Log out of any iSCSI disks
    diskutil.release_ibft_disks()

    # stop logging to tty3:
    logger.closeLogs()

    return reboot


if __name__ == "__main__":
    reboot = main(util.splitArgs(sys.argv[1:], ('--console', '--map_netdev', '--mount')))
    if reboot:
        os.system("reboot")
