#!/usr/bin/env python
###
# TIME UTILITY
# For use by clean installer so that we can avoid uClibc's 
# time functions.
#
# written by Andrew Peace
# Copyright XenSource UK Ltd. 2006

import sys
import os
import datetime
import time

def getLocalNow(timezone = None):
    if timezone:
        os.environ['TZ'] = timezone
        time.tzset()

    now = datetime.datetime.now()
    
    second = now.second
    minute = now.minute
    hour = now.hour
    day = now.day
    month = now.month
    year = now.year

    timestring = "%04d-%02d-%02d %02d:%02d:%02d" % \
                 (year, month, day, hour, minute, second)
    print timestring

def setLocal(timestring, timezone = None):
    if timezone:
        os.environ['TZ'] = timezone
        time.tzset()

    os.system("date --set='%s'" % timestring)

def usage():
    print "Usage: timeutil getLocalNow [timezone]"
    print "    or timeutil setLocal <time> [timezone]"
    print
    print "<time> is YYYY-MM-DD HH:mm:SS"    
    
def main():
    if len(sys.argv) == 1:
        usage()
    else:
        if sys.argv[1] == 'getLocalTime':
            if len(sys.argv) == 3:
                getLocalNow(sys.argv[2])
            else:
                getLocalNow()
        elif sys.argv[1] == 'setLocalTime':
            if len(sys.argv) == 4:
                setLocal(sys.argv[2], sys.argv[3])
            else:
                setLocal(sys.argv[2])
        else:
            usage()

if __name__ == '__main__':
    main()
