#!/bin/sh
#
# early-blacklist: disable some module blacklisting
#

udevadm trigger
udevadm settle --timeout=180

# enable all devices and discover again
echo -n '.'
rm -f /etc/modprobe.d/early-blacklist.conf
udevadm control --reload
udevadm trigger
udevadm settle --timeout=180
