#!/bin/bash
# Copyright (c) 2005-2006 XenSource, Inc. All use and distribution of this 
# copyrighted material is governed by and subject to terms and conditions 
# as licensed by XenSource, Inc. All other rights reserved.
# Xen, XenSource and XenEnterprise are either registered trademarks or 
# trademarks of XenSource Inc. in the United States and/or other countries.

###
# XEN CLEAN INSTALLER
# Startup script
#
# by Andrew Peace

# load USB modules before the shell or the installer:
usb-discover

args=`sed -e 's/\([^ ][^ ]*\)/--\1/g' /proc/cmdline`
export LVM_SYSTEM_DIR=/tmp/lvm

# force TERM if on a serial console (Xen defeats init's attempt to do this)
term=vt102
bash_shell=0
for arg in `sed -e 's/ $//; y/ /\n/' /proc/cmdline`; do
  case "$arg" in
    boot-console=*)
      serial_console=${arg#boot-console=};;
    console=*)
      console=${arg#console=};;
    term=*)
      term=${arg#term=};;
    bash-shell)
      bash_shell=1;;
  esac
done

[ -z "$serial_console" ] && serial_console="$console"
if expr "$serial_console" : 'ttyS' >/dev/null; then
  export TERM=$term
fi

if [ $bash_shell -eq 1 ]; then
    echo "Exiting this shell will run the installer:"
    echo " /opt/xensource/installer/init $args"
    echo "---"
    /bin/bash
fi

/opt/xensource/installer/init $args
