#!/bin/sh

debug=0

start()
{
  # build blacklist of legacy IDE drivers
    for file in /lib/modules/*/kernel/drivers/ide/*.ko; do
      b=`basename $file .ko`
      echo "blacklist $b" >>/etc/modprobe.d/ide-blacklist.conf
    done

  for arg in `sed -e 's/ $//; y/ /\n/' /proc/cmdline`; do
    case "$arg" in
      blacklist=*)
        # build user blacklist
        for mod in `echo ${arg#blacklist=} | tr ',' ' '`; do
	  echo "blacklist $mod" >>/etc/modprobe.d/user-blacklist.conf
	done;;
      enable-ide)
        rm -f /etc/modprobe.d/ide-blacklist.conf;;
      extramodules=*)
        extramodules=`echo ${arg#extramodules=} | tr ',' ' '`;;
    esac
  done

  # create temp blacklist to prevent fibre channel disks
  for mod in bfa lpfc qla2xxx qla4xxx fnic csiostor; do
    echo "blacklist $mod" >>/etc/modprobe.d/temp-blacklist.conf
  done

  # update temp blacklist to prevent USB disks
  for mod in ohci_hcd uhci_hcd ehci_pci xhci_hcd; do
    echo "blacklist $mod" >>/etc/modprobe.d/temp-blacklist.conf
  done

  mount -t ramfs udev /dev
  mkdir -p /dev/pts
  mount -t devpts none /dev/pts                     

  # create essential initial devices
  mknod -m 666 /dev/null c 1 3
  mknod -m 666 /dev/zero c 1 5
  mknod -m 600 /dev/console c 5 1

  echo -n "Detecting hardware."
  export UDEVD_MAX_CHILDS=1
  export UDEVD_MAX_CHILDS_RUNNING=64
  udevd --daemon
  udevtrigger
  udevsettle --timeout=180

  # repeat after deleting temp blacklist
  echo -n '.'
  rm -f /etc/modprobe.d/temp-blacklist.conf
  udevtrigger
  udevsettle --timeout=180

  # load extra modules from command line
  for mod in $extramodules; do
    echo "Loading module: $mod"
    modprobe $mod
  done

  # need dm-mod for P2V:
  echo -n '.'
  modprobe ata-generic all_generic_ide=1 2>/dev/null
  modprobe dm-mod
  udevsettle --timeout=180
  echo

  return 0
}

stop()
{
  killall udevd
  umount /dev
  return 0
}


RET=0
case "$1" in
  start)
    start
    RET=$?;;
  stop)
    stop
    RET=$?;;
  *)
    echo "Usage: $0 start|stop"
    RET=1
esac

exit $RET
